[package]
name = "advanced"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
slint = { version = "1.15", features = ["compat-1-2"] }
slint-node-editor = { path = "../../" }

[build-dependencies]
slint-build = "1.15"
