[package]
name = "advanced"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
slint = { workspace = true }
slint-node-editor = { workspace = true }

[build-dependencies]
slint-build = { workspace = true }
